// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package models

type Usuario struct {
	Id       string `json:"id"`
	Nome     string `json:"nome"`
	Email    string `json:"email"`
	Password string `json:"password"`
}
